var teacherRoutine=`
{
    "Idmohmmad Ali":[
        {
            "Bell":1,
            "Class":"Class1-2",
            "Subject":"Hindi(T.B.)"
        },
        {
            "Bell":4,
            "Class":"Class1-2",
            "Subject":"English"
        },
        {
            "Bell":4,
            "Class":"Class3",
            "Subject":"English(R)"
        },
        {
            "Bell":6,
            "Class":"Class5",
            "Subject":""
        }
    ],
    "Lalan Yadav":[
        {
            "Bell":1,
            "Class":"Class5",
            "Subject":"Hindi(W.B.)"
        },
        {
            "Bell":6,
            "Class":"Class1-2",
            "Subject":"Math(W.B.)"
        },
        {
            "Bell":3,
            "Class":"Class3",
            "Subject":"Math"
        },
        {
            "Bell":1,
            "Class":"Class5",
            "Subject":"Hindi(T.B)"
        },
        {
            "Bell":5,
            "Class":"Class5",
            "Subject":""
        }
    ],
    "Priti Kumari":[
        {
            "Bell":1,
            "Class":"Class4",
            "Subject":""
        },
        {
            "Bell":2,
            "Class":"Class3",
            "Subject":"Hindi(W.B.)"
        },
        {
            "Bell":3,
            "Class":"Class1-2",
            "Subject":"Math"
        },
        {
            "Bell":5,
            "Class":"Class3",
            "Subject":""
        },
        {
            "Bell":6,
            "Class":"Class4",
            "Subject":""
        }
    ],
    "Vijay Kumar":[
        {
            "Bell":5,
            "Class":"Class1-2",
            "Subject":"Hindi(R)"
        },
        {
            "Bell":7,
            "Class":"Class5",
            "Subject":""
        }
    ],
    "Sanjay Kumar":[
        {
            "Bell":1,
            "Class":"Class3",
            "Subject":"Hindi(T.B.)"
        },
        {
            "Bell":4,
            "Class":"Class3",
            "Subject":"English(R)"
        },
        {
            "Bell":5,
            "Class":"Class7",
            "Subject":"Hindi"
        }
    ],
    "Anshu Kumari":[
        {
            "Bell":1,
            "Class":"Class6",
            "Subject":"Social Studies"
        },
        {
            "Bell":2,
            "Class":"Class7",
            "Subject":"Social Studies"
        },
        {
            "Bell":6,
            "Class":"Class8",
            "Subject":"Social Studies"
        },
        {
            "Bell":7,
            "Class":"Class6",
            "Subject":"Optional"
        }
    ],
    "AK Verma":[
        {
            "Bell":2,
            "Class":"Class6",
            "Subject":"Sanskrit"
        },
        {
            "Bell":4,
            "Class":"Class10",
            "Subject":"Sanskrit"
        },
        {
            "Bell":5,
            "Class":"Class9",
            "Subject":"Sanskrit"
        },
        {
            "Bell":7,
            "Class":"Class7",
            "Subject":"Optional"
        }
    ],
    "Kuman Kumar":[
        {
            "Bell":1,
            "Class":"Class7",
            "Subject":"Math"
        },
        {
            "Bell":3,
            "Class":"Class6",
            "Subject":"Math"
        },
        {
            "Bell":5,
            "Class":"Class10",
            "Subject":"Hindi"
        },
        {
            "Bell":6,
            "Class":"Class9",
            "Subject":"Math"
        }
    ],
    "Sumit Kumar":[
        {
            "Bell":3,
            "Class":"Class8",
            "Subject":"English"
        },
        {
            "Bell":4,
            "Class":"Class7",
            "Subject":"English"
        },
        {
            "Bell":5,
            "Class":"Class6",
            "Subject":"English"
        },
        {
            "Bell":7,
            "Class":"Class10",
            "Subject":"English(R.W.)"
        }
    ],
    "Anuradha Tiwari":[
        {
            "Bell":2,
            "Class":"Class10",
            "Subject":"Science"
        },
        {
            "Bell":3,
            "Class":"Class9",
            "Subject":"Science"
        },
        {
            "Bell":6,
            "Class":"Class6",
            "Subject":"Science"
        }
    ],
    "Rani Kumari":[
        {
            "Bell":3,
            "Class":"Class7",
            "Subject":"Science"
        },
        {
            "Bell":4,
            "Class":"Class12",
            "Subject":"Home Science"
        },
        {
            "Bell":5,
            "Class":"Class8",
            "Subject":"Science"
        },
        {
            "Bell":7,
            "Class":"Class11",
            "Subject":"Home Science"
        }
    ],
    "Prabha Kumari":[
        {
            "Bell":2,
            "Class":"Class8",
            "Subject":"Hindi"
        },
        {
            "Bell":3,
            "Class":"Class11",
            "Subject":"Hindi"
        },
        {
            "Bell":5,
            "Class":"Class12",
            "Subject":"Hindi"
        },
        {
            "Bell":6,
            "Class":"Class7",
            "Subject":"Hindi"
        }
    ],
    "AK Singh":[
        {
            "Bell":1,
            "Class":"Class8",
            "Subject":"Sanskrit"
        },
        {
            "Bell":4,
            "Class":"Class6",
            "Subject":"Hindi"
        },
        {
            "Bell":5,
            "Class":"Class7",
            "Subject":"Sanskrit"
        },
        {
            "Bell":7,
            "Class":"Class8",
            "Subject":"Optional"
        }
    ],
    "Rajneesh Kumar":[
        {
            "Bell":1,
            "Class":"Class9",
            "Subject":"Math"
        },
        {
            "Bell":3,
            "Class":"Class10",
            "Subject":"Math"
        },
        {
            "Bell":4,
            "Class":"Class8",
            "Subject":"Math"
        },
        {
            "Bell":6,
            "Class":"Class12",
            "Subject":"Math"
        }
       
    ],
    "Bharat Paswan":[
        {
            "Bell":1,
            "Class":"Class10",
            "Subject":"English"
        },
        {
            "Bell":2,
            "Class":"Class9",
            "Subject":"English"
        },
        {
            "Bell":3,
            "Class":"Class12",
            "Subject":"English"
        },
        {
            "Bell":6,
            "Class":"Class11",
            "Subject":"English"
        }
    ],
    "Anjali Kumari":[
        
        {
            "Bell":4,
            "Class":"Class9",
            "Subject":"Social Studies"
        },
        {
            "Bell":5,
            "Class":"Class11",
            "Subject":"Geography"
        },
        {
            "Bell":6,
            "Class":"Class10",
            "Subject":"Geography"
        },
        {
            "Bell":7,
            "Class":"Class12",
            "Subject":"Geography"
        }
    ],
    "Neetu Kumari":[
        {
            "Bell":1,
            "Class":"Class11",
            "Subject":"Pol Science"
        },
        {
            "Bell":2,
            "Class":"Class12",
            "Subject":"Pol Science"
        },
        {
            "Bell":4,
            "Class":"Class11",
            "Subject":"Psychology"
        },
        {
            "Bell":6,
            "Class":"Class12",
            "Subject":"Psychology"
        }
    ],
    "Pinky Soni":[
        {
            "Bell":1,
            "Class":"Class12",
            "Subject":"History"
        },
        {
            "Bell":2,
            "Class":"Class11",
            "Subject":"History"
        },
        {
            "Bell":4,
            "Class":"Class12",
            "Subject":"Soci"
        },
        {
            "Bell":7,
            "Class":"Class11",
            "Subject":"Soci"
        }
    ]
}
`